### ISSUE TITLE
Dialog wybierania plików

### ISSUE THREAD

**Issue by JaKafka** [aSliwska/typed-text-reader#2]
Defaultowo ma filtr na .png, podczas gdy wspiera inne pliki, lepiej by defaultowo pytał o dowolny wspierany format.
@aSliwska  

![image](https://github.com/aSliwska/typed-text-reader/assets/152932575/520d46c7-bd0c-4a8a-a72b-8e181f0f5295)

**Comment by aSliwska** [comment]
Dodam, żeby defaultowy był .*, ale muszę sprawdzić, czy jestem w stanie przyjmować każdy typ i go konwertować, bo: 

> Supported image formats include JPEG, PNG, GIF, SVG, or m-by-n-by-3 truecolor image array.

[z dokumentacji uiimage](https://www.mathworks.com/help/matlab/ref/uiimage.html#mw_b8f849ae-4b5f-4f2b-baa4-e8019437dd58). Mimo wszystko muszę być w stanie wyświetlić obraz w UI.

**Comment by JaKafka** [comment]
Można by też było przerzucić obsługę plików na UI a separator zajął by się już tylko separacją z macierzy obrazu w skali szarości

**Comment by aSliwska** [comment]
Wszystko zrobione w najnowszym pull requescie, jedyna różnica taka (bo zapomniałam), że separator dostaje obrazek z imread() a nie w skali szarości (ale jest sprawdzone że na pewno może być przekonwertowany)
